### ISSUE TITLE
Most API calls crash by `generatePwHash(maybePw).compare(hash)`

### ISSUE THREAD

**Issue by nebaughman** [blockchain/service-my-wallet-v3#52] opened 2016-02-28 00:57 UTC
The `/login` call worked. Then calling `/list` crashed:

```
TypeError: Object Bï¿½ \ï¿½?ï¿½}ï¿½K(
{ï¿½fnï¿½_ï¿½ï¿½ï¿½ï¿½ZA ï¿½qï¿½P has no method 'compare'
   at validatePassword (/usr/local/lib/node_modules/blockchain-wallet-service/src/wallet-cache.js:128:34)
   at WalletCache.getWallet (/usr/local/lib/node_modules/blockchain-wallet-service/src/wallet-cache.js:98:17)
   at MerchantAPI.getWallet (/usr/local/lib/node_modules/blockchain-wallet-service/src/api.js:15:21)
   at MerchantAPI.listAddresses (/usr/local/lib/node_modules/blockchain-wallet-service/src/api.js:31:15)
   at /usr/local/lib/node_modules/blockchain-wallet-service/src/server.js:176:32
   at Layer.handle [as handle_request] (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/express/lib/router/layer.js:95:5)
   at next (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/express/lib/router/route.js:131:13)
   at /usr/local/lib/node_modules/blockchain-wallet-service/src/server.js:189:5
   at Layer.handle [as handle_request] (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/express/lib/router/layer.js:95:5)
   at next (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/express/lib/router/layer.js:95:5)
   at /usr/local/lib/node_modules/blockchain-wallet-service/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/express/lib/router/index.js:330:12)
   at next (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/express/lib/router/index.js:271:10)
   at /usr/local/lib/node_modules/blockchain-wallet-service/src/server.js:201:5
   at Layer.handle [as handle_request] (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/express/lib/router/index.js:312:13)
   at /usr/local/lib/node_modules/blockchain-wallet-service/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/express/lib/router/index.js:330:12)
   at next (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/express/lib/router/index.js:271:10)
   at urlencodedParser (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/body-parser/lib/types/urlencoded.js:88:40)
   at Layer.handle [as handle_request] (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/express/lib/router/index.js:312:13)
   at /usr/local/lib/node_modules/blockchain-wallet-service/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/express/lib/router/index.js:330:12)
   at next (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/express/lib/router/index.js:271:10)
   at jsonParser (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/body-parser/lib/types/json.js:100:40) 
```
```
function generatePwHash(pw) {
  var iterations = 5000;
  return crypto.pbkdf2Sync(pw, randomBytes, iterations, BYTES_PER_HASH, 'sha256');
}

function validatePassword(hash, maybePw) {
  if (!Buffer.isBuffer(hash) || !maybePw) return false;
  return generatePwHash(maybePw).compare(hash) === 0;
}
```

This is on Ubuntu Server 14.04 following the install instructions (including the `default-jdk`). Whatever object is returned from `crypto.pbkdf2Sync` has no `compare` method.

Calling `/balance` has the same result. Password is definitely correct (using a bogus password generates the same result).

**Comment by jtormey** [comment] 2016-02-28 21:22
This is probably caused by being on an old version of node. `crypto.pbkdf2Sync` returns a `Buffer`, which doesn't have `compare` until node 0.12. See #14.

I'll make a todo to catch this error and output more useful feedback.

**Comment by nebaughman** [comment] 2016-02-28 21:22
This was caused by an old version of nodejs/npm. The Ubuntu 14.04 repositories only provide nodejs v0.10.x, not the required v0.12.x.

I followed instructions similar to this article on installing via NVM:

https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server

**Comment by nebaughman** [comment] 2016-02-28 21:23
(Just beat me to the punch @jtormey - we were typing at the same time).

**Comment by nebaughman** [comment] 2016-02-28 21:25
#51 is also resolved if nodejs/npm installed via NVM (within non-root user account)

**Comment by jtormey** [comment] 2016-02-28 21:26
Good to know, thanks! NVM is a great tool, I'll include a note in the README about it.

**Comment by jtormey** [comment] 2016-03-07 14:20
Closing since [a note was added](https://github.com/blockchain/service-my-wallet-v3/commit/1c10835d60f7feb2183e6427cf64ea20277abcef) in the README concerning this issue.

**Closed by jtormey** 2016-03-07 14:20 UTC
