### ISSUE TITLE
Error: ERR_TIMEOUT - while fetching balance of second wallet.

### ISSUE THREAD

**Issue by balajilandge** [blockchain/service-my-wallet-v3#164] opened 2017-01-24 11:37 UTC
[node -> v6.9.1, npm -> 2.15.11, blockchain-wallet-service-> 0.22.3]

Once the wallet-service is started I am able to fetch the balance for only one wallet but when I am trying to fetch balance for another wallet getting timed out error as below. In order to fetch the balance for another wallet I have to restart the service again. Please help in this regard.

{"error":"Request to fetch wallet timed out, check that your API key is correct"}

Steps to reproduce the above errors as below.

Step 1 - Start the service 
blockchain-wallet-service start --port 3000

Step 2 - Fetch wallet-1 balance (works)
http://localhost:3000/merchant/9fcb29f1-1955-46b6-9a01-8f270ed081a3/balance?password=WalletPassword1

Step 3 - Fetch wallet-2 balance (Time Out Error)
http://localhost:3000/merchant/bb95f2b6-9f6b-4062-a7b7-794a9431d155/balance?password=WalletPassword2

Step 4 - Repeat Step-2 Fetch wallet-1 balance (works again)

Step 5 - optional step -Execute create wallet (works)

Step 6 - Repeat Step-3 Fetch wallet-2 balance (Time Out Error again)

Step 7 - list addresses on  wallet-1 (works)
http://localhost:3000/merchant/9fcb29f1-1955-46b6-9a01-8f270ed081a3/list?password=WalletPassword1

Step 7 - list addresses on  wallet-2 (Time Out Error)
http://localhost:3000/merchant/bb95f2b6-9f6b-4062-a7b7-794a9431d155/list?password=WalletPassword2

Thanks!

**Comment by jtormey** [comment] 2017-01-26 16:30
Hi, I'm having some trouble reproducing this issue. Using node@6.9.1, npm@2.15.11, and service@0.22.3 I'm able to log in to multiple wallets simultaneously without a problem. I'll keep trying and comment here if I find anything.

What environment are you running this in? (Windows, Linux distro, etc, just so that I have a better scope of the issue.)

**Comment by jtormey** [comment] 2017-01-26 16:32
Also, do either of the wallets you're using have any special security settings? For example, verified email or 2FA protection.

**Comment by balajilandge** [comment] 2017-01-26 18:25
Hi, Thank you for your response.
The Answer to your first question is, I am using Window environment and tested above issue on windows 7 and windows server machine.  The dummy wallets I used in above steps were created using create wallet API no wallets had any security features enable when I tested it. Now I can see that someone added his email to first wallet, that is strange. But that should not stop anybody from recreating this issue. You can take any of two wallets and reproduce this issue. Thanks.

**Comment by jtormey** [comment] 2017-01-26 19:08
Thanks for the info, I'm able to reproduce consistently on a Windows 10 desktop machine. Will close when I've found the root cause and pushed a fix.

**Closed** 2017-01-26 23:22 UTC
Labels: bug, platform: windows

**Comment by balajilandge** [comment] 2017-01-27 14:58
Fix tested OK. Thank you for quick fix.

**Comment by jtormey** [comment] 2017-01-27 15:43
No problem, thanks for reporting. Fix is now live in v0.22.4.
